don't do an extra yarn install in docker land
this makes it so building the web container succeeds without having to
tweak the Dockerfile. i.e. no more:

  Error: ENOENT: no such file or directory, scandir '/usr/src/app/node_modules/node-sass/vendor'

i'm still not sure why the extra yarn install causes that, but it does :shrug:

test plan:
`docker-compose build web` should succeed

Change-Id: I5120dd0ea6168d7d373364bccd02bfa990df54d5
Reviewed-on: https://gerrit.instructure.com/111953
Tested-by: Jenkins
Reviewed-by: Landon Wilkins <lwilkins@instructure.com>
Product-Review: Landon Wilkins <lwilkins@instructure.com>
QA-Review: Landon Wilkins <lwilkins@instructure.com>