spec: fix selenium transaction stomping
refactor into a single monitor so that no db stuff happens in the spec
thread while a request is in progress. additionally lock at the transaction
level (if there is one) so that one thread doesn't stomp the @transaction
from the other thread (Mutex -> Montitor for reentrancy)

test plan:
1. specs should all pass
2. there should be no weird transaction stomping anymore, e.g.
   * undefined method `rollback' for #<ActiveRecord::ConnectionAdapters...>
   * PG::InFailedSqlTransaction: ERROR:  current transaction is aborted...
   * etc

Change-Id: Ib4af4dc9e8215c8e31e9c9cb6799df894b71f067
Reviewed-on: https://gerrit.instructure.com/69976
Tested-by: Jenkins
Product-Review: Jon Jensen <jon@instructure.com>
QA-Review: Jon Jensen <jon@instructure.com>
Reviewed-by: Shawn Meredith <shawn@instructure.com>
Reviewed-by: Cody Cutrer <cody@instructure.com>